// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Runtime settings override build-time env vars so the app works without a
// pre-configured .env (demo / self-hosted mode).
const SUPABASE_URL =
  localStorage.getItem('cc_supabase_url') ||
  (import.meta.env.VITE_SUPABASE_URL as string | undefined) ||
  '';
const SUPABASE_PUBLISHABLE_KEY =
  localStorage.getItem('cc_supabase_anon_key') ||
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined) ||
  '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);